```{r}
library(tidyverse)

#visualization
library(ggplot2)
library(plotly)
library(hrbrthemes)
library(leaflet)

#time series
library(xts)
library(astsa)
library(forecast)
library(tsbox)
library(tseries)
```

#Importing

```{r}
#data frame of county locations (not merged)
county_locations = read.csv('CDC_county_locations.csv')

#CDC data with no missing values
cdc_nomissing_2020 = read.csv('CDC_no_missing09_12_2020.csv')

#One hot encoded; no missing values
cdc_encoded = read.csv('CDC_encoded.csv')
```

#Merging geo data with main data

```{r}
glimpse(county_locations)
glimpse(cdc_encoded)

cdc_main = left_join(cdc_encoded, county_locations, by = c("res_county" = "county"))
glimpse(cdc_main)

#Merged successfully 

#View(county_locations)
#cdc_main$res_county
#cdc_main %>% filter(res_county == "Polk") %>% select(res_county,lon,lat)
```

#Leaflet map

```{r}
#cdc_main$

map_subs = leaflet(data = cdc_main) %>% 
  addProviderTiles(providers$CartoDB.DarkMatterNoLabels) %>% 
  addCircleMarkers(~ lon, ~lat, color = "orange", weight = 1, radius = 1, fillOpacity = 0.5, opacity = 1,
                   label = paste("Name:", cdc_main$current_status))

map_subs

```