```{r, messages = FALSE}
library(tidyverse)

#visualization
library(ggplot2)
library(plotly)
library(hrbrthemes)

#time series
library(xts)
library(astsa)
library(forecast)
library(tsbox)
library(tseries)
```

#IMPORT DATA
```{r}
cdc_dec20_zoo = read.csv('cdc_dec20_ts.csv') %>% 
  rename(Date = X2020.01.01, Values = X2)

cdc_preNov_zoo = cdc_dec20_zoo %>% 
  mutate(Date = as.Date(Date)) %>% 
  filter(Date <= as.Date("2020-10-31"))

cdc_Nov2020_zoo = cdc_dec20_zoo %>% 
  mutate(Date = as.Date(Date)) %>% 
  filter(Date > as.Date("2020-10-31")) 


```

#time series - base plot
```{r}
plot(cdc_preNov_zoo, type = 'l')
```
#time series - ggplot
```{r}
ggplot(data = cdc_preNov_zoo, aes(x = Date, y = Values)) +
  geom_line() +
  xlab("")
```

# Detrending by differencing
```{r}
cdc_d2_ts = diff(cdc_preNov_zoo$Values, lag = 1, differences = 1)
cdc_preNov_zoo = cdc_preNov_zoo %>% mutate(diff = c(NA,cdc_d2_ts))
#na.omit(cdc_d2_ts)
  
plot(cdc_d2_ts, type = 'l')
ggplot(data = as.data.frame(cdc_preNov_zoo), aes(x = Date, y = diff)) +
  geom_line() +
  xlab("")
```

```{r}
adf.test(na.omit(cdc_preNov_zoo$diff))
```

```{r}
acf(na.omit(cdc_preNov_zoo$diff))
```

```{r}
pacf(na.omit(cdc_preNov_zoo$diff))
```

```{r}
# arima has a auto.arima function which gives us the ideal arima model based on our data.
cdc_arima <- auto.arima(na.omit(cdc_preNov_zoo$diff))
cdc_arima


```

```{r}
# lets use the auto.arima function to forecast 3 weeks

forecast1 <- forecast(cdc_arima, h=32)
additional_positive_cases <- round(sum(forecast1$upper[,2]),0)
# [1] 230735

sum(cdc_Nov2020_zoo$Values)
# 567021

total_number_of_cases <- round(sum(cdc_preNov_zoo$Values)+additional_positive_cases,0)
# # [1] 2533845

plot(forecast1)

```

```{r}

# lets use the auto.arima function to forecast 3 months
forecast2 <- forecast(object = cdc_arima, h = 90)
#additional_deaths2 <- round(sum(forecast2$upper[,2]),0)
# [1] 82653

#total_number_of_deaths2 <- round(sum(dat_US_Analysis$new_deaths)+additional_deaths2,0)
# [1] 235967
plot(forecast2)
```

# Model Evaluation

```{r}
accuracy(cdc_arima)
```

```{r}
modelcv = CVar(na.omit(cdc_preNov_zoo$diff), k = 5, lambda = 0.15)
print(modelcv)
```

#Work on this later

```{r}
# autoplot(ts(cdc_preNov_zoo$diff), series = "Data") +
#   autolayer(modelcv$testfit, series = "Fits") +
#   autolayer(modelcv$residuals, series = "Residuals")
# 
# ggAcf(modelcv$residuals)
```

```{r}
# cdc_arima %>% 
#   forecast(h = 21) %>% 
#   autoplot() 

ggplot(cdc_preNov_zoo, aes(x = Date, y = Values)) + geom_line() + 
  geom_line(data = cdc_Nov2020_zoo, color = "red")
```

```{r}
plot(forecast1)
lines(forecast1$x)

plot()
```
